name: Create Cluster

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v4
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: "kind"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Get kubeconfig
        run: kind get kubeconfig > kubeconfig
      - name: What dir am I in??
        run: pwd && ls
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply --auto-approve
      - name: Wait for Grafana Deployment
        run: kubectl rollout status deployment/grafana --namespace=grafana
      - name: Get Grafana Deployment Logs
        run: kubectl logs deployment/grafana --namespace=grafana
      - name: Check Grafana Namespace
        run: kubectl get all --namespace=grafana