name: Create Cluster

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v4
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: "kind"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Get kubeconfig
        run: kind get kubeconfig > kubeconfig
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply --auto-approve
      - name: Wait for Grafana Deployment
        run: kubectl rollout status deployment/grafana --namespace=grafana
      - name: Get Grafana Deployment Logs
        run: kubectl logs deployment/grafana --namespace=grafana --tail=10
      - name: Check Grafana Namespace
        run: kubectl get all --namespace=grafana
      - name: Check service API health
        run: | 
          # Check Grafana Health API Endpoint
          curl http://admin:admin@localhost:3000/api/health
          # Check Grafana Organization API Endpoint
          curl http://admin:admin@localhost:3000/api/org
          # End port forward
          kill %1